language: scala

jobs:
  include:
    - scala: 2.11.12
      jdk: openjdk8
      script:
        - sbt clean coverage "++$TRAVIS_SCALA_VERSION test" coverageReport

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wget cmake protobuf-compiler
  - protoc --version

after_success:
  - bash <(curl -s https://codecov.io/bash)